TEXTS = {
    "ua": {
        "start_message": "Привіт, я бот персональних рекомендацій для проекту Cinotes. Тисни /help для отримання інструкцій",
        "user_not_in_db_error": "Виникла помилка всередині бота, відправ /start",
        "language_message": "Обрана мова: Українська",
        "help_message": "<b>Пізніше</b> <i>тут</i> <code>щось</code> буде...",
        "press_button_to_login": "Просто натисни на кнопку внизу",
        "login_button_text": "Авторизуватися",
        "trying_login": "Намагаюсь авторизуватися...",
        "wrong_email": "Виникла помилка: вказано неправильну пошту",
        "wrong_password": "Виникла помилка: вказано неправильний пароль",
        "unknown_server_error": "Виникла невідома помилка на сервері",
        "success_login": "Успішно авторизований!",
        "jwt_expire_on": "Токен авторизації дійсний до: {dt}",
        "user_is_basic": "Тобі недоступна система рекомендацій. Щоб отримати доступ, придбай преміум-підписку на сайті або у додатку",
        "user_is_admin": "Твій акаунт розпізнано як адміністративний. Тобі будуть доступні деякі додаткові функції, детальніше: /admin",
        "user_is_premium": "Дякуємо за преміум-підписку. Бота успішно підключено!",
        "unknown_bot_error": "Виникла невідома помилка в боті",
        "not_authorized": "Щоб використовувати цю функцію, спочатку потрібно автоизуватися",
        "token_not_valid": "Термін дії токену авторизації сплинув або токен не валідний. Перевір, що акаунт підтверджено та авторизуйся знову за допомогою команди /login",
        "more_info_button_text": "Детальніше",
        "film_not_found": "Схоже, такого фільму наразі немає",
        "full_info_text": "{name}\n\nКраїна: {country}\nДата виходу: {release_date}\nНаш рейтинг: {rating}\nIMDB рейтинг: {imdb_rating}\nЖанри: {genres}\nСтудія: {studio}\nРежисер: {director}",
        "admin_message": "Доступні команди для адміністраторів:\n\n/stat - отримання статистики бота",
        "stat_message": "Користувачів всього: {total_users}\n\nАкаунтів всього: {total_accounts}\nАдміністративних: {admin_accounts}\nПреміум: {premium_accounts}\n\nВсього рекомендацій: {total_recommendations}\nРекомендацій за сьогодні: {recommendations_today}",
        "get_unknown_text_message": "Я не розумію тебе. Відправ /start або /help",
        "get_unknown_type_of_message": "Я приймаю лише текстові повідомлення. Для отримання інструкцій натисни /help",
    },
    "en": {
        "start_message": "Hi, I'm a personal recommendation bot for the Cinotes project. Press /help for instructions",
        "user_not_in_db_error": "An error occurred inside the bot, send /start",
        "language_message": "Choosen language: English",
        "help_message": "<b>Later</b> <i>here</i> <code>something</code> will be...",
        "press_button_to_login": "Just click the button below",
        "login_button_text": "Log in",
        "trying_login": "Trying to log in...",
        "wrong_email": "An error occurred: Invalid email address",
        "wrong_password": "An error occurred: The password is incorrect",
        "unknown_server_error": "An unknown server error has occurred",
        "success_login": "Successfully authorized!",
        "jwt_expire_on": "The authorization token is valid until: {dt}",
        "user_is_basic": "The recommendation system is not available to you. To gain access, purchase a premium subscription on the website or in the app",
        "user_is_admin": "Your account is recognized as administrative. Some additional functions will be available to you, more details: /admin",
        "user_is_premium": "Thank you for your premium subscription. Bot connected successfully!",
        "unknown_bot_error": "An unknown bot error has occurred",
        "not_authorized": "To use this feature, you must first log in",
        "token_not_valid": "The authorization token has expired or the token is invalid. Check that the account is verified and log in again using the /login command",
        "more_info_button_text": "More details",
        "film_not_found": "It seems that there is no such movie at the moment",
        "full_info_text": "{name}\n\nCountry: {country}\nRelease date: {release_date}\nOur rating: {rating}\nIMDB rating: {imdb_rating}\nGenre: {genres}\nStudio: {studio}\nDirector: {director}",
        "admin_message": "Available commands for administrators:\n\n/stat - getting bot statistics",
        "stat_message": "Total users: {total_users}\n\nTotal accounts: {total_accounts}\nAdministrative: {admin_accounts}\nPremium: {premium_accounts}\n\nTotal recommendations: {total_recommendations}\nRecommendations for today: {recommendations_today}",
        "get_unknown_text_message": "I don't understand you. Send /start or /help",
        "get_unknown_type_of_message": "I only accept text messages. Click /help for instructions",
    }
}